# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'fr'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    WeatherApp\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    WeatherApp\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    WeatherApp\Utils\Weather:
        arguments:
            - '@csa_guzzle.client.weather'
            - '@serializer'
            - '%env(resolve:OPENWEATHER_API_KEY)%'

# Handlers

    WeatherApp\Command\GetWeatherDataForTileQueryHandler:
        public: true
        tags:
            - { name: command_handler, handles: WeatherApp\Command\GetWeatherDataForTileQuery }

    WeatherApp\Command\CreateTileCommandHandler:
        public: true
        tags:
            - { name: command_handler, handles: WeatherApp\Command\CreateTileCommand }

    WeatherApp\Command\DeleteTileCommandHandler:
        public: true
        tags:
            - { name: command_handler, handles: WeatherApp\Command\DeleteTileCommand }

    WeatherApp\Command\GetTileQueryHandler:
        public: true
        tags:
            - { name: command_handler, handles: WeatherApp\Command\GetTileQuery }

    WeatherApp\Command\GetTilesQueryHandler:
        public: true
        tags:
            - { name: command_handler, handles: WeatherApp\Command\GetTilesQuery }