WeatherApp\Entity\Tile:
    type: entity

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:

        city:
            name:
                type: string
                length: 53
                nullable: false

        latitude:
            name:
                type: float
                nullable: false

        longitude:
            name:
                type: float
                nullable: false
